# Disable bundled observability backends
grafana:
  enabled: false

prometheus:
  enabled: false

jaeger:
  enabled: false

opensearch:
  enabled: false

# Disable default bundled Collector
opentelemetry-collector:
  enabled: false

# Override environment variables globally across all components
default:
  envOverrides:
    - name: OTEL_SDK_DISABLED
      value: "true"

# Use a locally built image for the email component
components:
  email:
    imageOverride:
      repository: email
      tag: local
      pullPolicy: Never